issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  disable-all: true
  enable:
  - errorlint
  - gocritic
  - gofmt
  - goimports
  - gomodguard
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - revive
  - testifylint
linters-settings:
  gocritic:
    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint run` to see all tags and checks.
    # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - diagnostic
      - opinionated
      - style
    disabled-checks:
      - paramTypeCombine
      - unnamedResult
      - whyNoLint
  gomodguard:
    blocked:
      modules:
      - github.com/pkg/errors:
          recommendations:
          - errors
          - fmt
  testifylint:
    disable:
    - float-compare
    - go-require
    enable:
    - bool-compare
    - compares
    - empty
    - error-is-as
    - error-nil
    - expected-actual
    - len
    - require-error
    - suite-dont-use-pkg
    - suite-extra-assert-call
run:
  timeout: 5m
