version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - depguard
    - errcheck
    - errorlint
    - gocritic
    - gocyclo
    - gomodguard
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    depguard:
      rules:
        all:
          deny:
            - pkg: gopkg.in/yaml.v2
              desc: compose-go uses go.yaml.in/yaml/v4
            - pkg: gopkg.in/yaml.v3
              desc: compose-go uses go.yaml.in/yaml/v4
            - pkg: github.com/stretchr/testify/assert
              desc: Use "gotest.tools/v3/assert" instead
            - pkg: github.com/stretchr/testify/require
              desc: Use "gotest.tools/v3/assert" instead
            - pkg: github.com/stretchr/testify/suite
              desc: Do not use
    gocritic:
      disabled-checks:
        - paramTypeCombine
        - unnamedResult
        - whyNoLint
      enabled-tags:
        - diagnostic
        - opinionated
        - style
    gomodguard:
      blocked:
        modules:
          - github.com/pkg/errors:
              recommendations:
                - errors
                - fmt
    lll:
      line-length: 200
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - paths/windows_path.go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
