/*
   Copyright 2020 The Compose Specification Authors.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

// Command containerspec generates types/container_spec_attributes.gen.go,
// the compile-time list of the container specification's yaml attributes.
// Reflection happens here, at generation time, so consumers get a plain
// source-level list that cannot drift from the ContainerSpec type as long
// as generation is part of the build validation.
package main

import (
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"

	"github.com/compose-spec/compose-go/v2/types"
)

func main() {
	var keys []string
	t := reflect.TypeOf(types.ContainerSpec{})
	for i := range t.NumField() {
		tag, _, _ := strings.Cut(t.Field(i).Tag.Get("yaml"), ",")
		if tag != "" && tag != "-" && !strings.HasPrefix(tag, "#") {
			keys = append(keys, tag)
		}
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("// Code generated by internal/generate/containerspec. DO NOT EDIT.\n\n")
	b.WriteString("package types\n\n")
	b.WriteString("// ContainerSpecAttributes lists the yaml attributes of ContainerSpec —\n")
	b.WriteString("// the boundary between the container specification and workload or\n")
	b.WriteString("// service-only attributes, as consumed by the pre_start inheritance\n")
	b.WriteString("// resolution.\n")
	b.WriteString("var ContainerSpecAttributes = []string{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%q,\n", k)
	}
	b.WriteString("}\n")

	if err := os.WriteFile("types/container_spec_attributes.gen.go", []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
